-- Criação da tabela Cliente
-- CREATE TABLE Cliente (
--     id BIGINT AUTO_INCREMENT PRIMARY KEY,
--     nome VARCHAR(255)
-- );
-- Inserindo dados na tabela Cliente
INSERT INTO Cliente (nome) VALUES ('João Silva');
INSERT INTO Cliente (nome) VALUES ('Maria Oliveira');
INSERT INTO Cliente (nome) VALUES ('José Flores');
INSERT INTO Cliente (nome) VALUES ('Ana Gomes');
INSERT INTO Cliente (nome) VALUES ('Beatriz Souza');
INSERT INTO Cliente (nome) VALUES ('Carlos Chagas');
INSERT INTO Cliente (nome) VALUES ('João Tavares');
INSERT INTO Cliente (nome) VALUES ('Joana Claro');
INSERT INTO Cliente (nome) VALUES ('Eduardo Teixeira');

-- Criação da tabela Fornecedor
-- create table fornecedor (
--     codigo bigint generated by default as identity,
--     razao_social varchar(255),
--     primary key (codigo)
-- );
-- Inserindo dados na tabela Fornecedor
INSERT INTO Fornecedor (razao_social) VALUES ('João Silva');
INSERT INTO Fornecedor (razao_social) VALUES ('Maria Oliveira');
INSERT INTO Fornecedor (razao_social) VALUES ('José Flores');
INSERT INTO Fornecedor (razao_social) VALUES ('Ana Gomes');
INSERT INTO Fornecedor (razao_social) VALUES ('Beatriz Souza');
INSERT INTO Fornecedor (razao_social) VALUES ('Carlos Chagas');
INSERT INTO Fornecedor (razao_social) VALUES ('João Tavares');
INSERT INTO Fornecedor (razao_social) VALUES ('Joana Claro');
INSERT INTO Fornecedor (razao_social) VALUES ('Eduardo Teixeira');

-- Inserindo dados na tabela Produto
INSERT INTO Produto (nome, preco) VALUES ('Café', 10.0);
INSERT INTO Produto (nome, preco) VALUES ('Leite', 5.5);
INSERT INTO Produto (nome, preco) VALUES ('Açúcar', 3.0);
INSERT INTO Produto (nome, preco) VALUES ('Pão', 2.0);
INSERT INTO Produto (nome, preco) VALUES ('Queijo', 15.0);

-- Criação da tabela Pedido
-- create table pedido (
--     data_inclusao date,
--     cliente_id bigint,
--     fornecedor_id bigint,
--     id bigint generated by default as identity,
--     primary key (id)
-- )
-- Inserindo dados na tabela Pedido
INSERT INTO Pedido (cliente_id, fornecedor_id, data_inclusao) VALUES (1, 1, '2024-10-01');
INSERT INTO Pedido (cliente_id, fornecedor_id, data_inclusao) VALUES (1, 1, '2024-10-05');
INSERT INTO Pedido (cliente_id, fornecedor_id, data_inclusao) VALUES (2, 1, '2024-10-10');
INSERT INTO Pedido (cliente_id, fornecedor_id, data_inclusao) VALUES (2, 1, '2024-10-01');
INSERT INTO Pedido (cliente_id, fornecedor_id, data_inclusao) VALUES (2, 1, '2024-10-05');
INSERT INTO Pedido (cliente_id, fornecedor_id, data_inclusao) VALUES (3, 1, '2024-10-10');
INSERT INTO Pedido (cliente_id, fornecedor_id, data_inclusao) VALUES (3, 1, '2024-10-01');
INSERT INTO Pedido (cliente_id, fornecedor_id, data_inclusao) VALUES (3, 1, '2024-10-05');
INSERT INTO Pedido (cliente_id, fornecedor_id, data_inclusao) VALUES (4, 1, '2024-10-10');
INSERT INTO Pedido (cliente_id, fornecedor_id, data_inclusao) VALUES (5, 1, '2024-10-01');
INSERT INTO Pedido (cliente_id, fornecedor_id, data_inclusao) VALUES (5, 1, '2024-10-05');
INSERT INTO Pedido (cliente_id, fornecedor_id, data_inclusao) VALUES (6, 1, '2024-10-10');




-- Criação da tabela Item_Pedido
-- create table item_pedido (
--     id bigint generated by default as identity,
--     pedido_id bigint,
--     produto_id bigint,
--     primary key (id)
-- )
-- drop table item_pedido;
-- create table item_pedido (
--     preco float(53) not null,
--     quantidade integer not null,
--     id bigint generated by default as identity,
--     pedido_id bigint,
--     produto_id bigint,
--     primary key (id)
-- );
-- Inserindo dados na tabela Item_Pedido
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (1, 1);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (1, 2);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (1, 3);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (1, 4);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (1, 5);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (2, 1);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (2, 2);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (2, 3);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (3, 1);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (3, 3);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (4, 1);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (4, 2);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (4, 3);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (4, 4);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (4, 5);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (5, 1);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (5, 2);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (5, 3);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (6, 1);
INSERT INTO item_pedido(pedido_id, produto_id) VALUES (6, 3);
